### PR TITLE
[FIX] pos_addons: fix OCA depends to Vauxoo depends

### PR DESCRIPTION
**Pull request by randall-vx**
* Set oca_depends url to vauxoo's forks.

cc: @luisg123v @moylop260

### CODE REVIEW

**Review by luisg123v — CHANGES_REQUESTED** [review]
@randall-vx,

I'd recommend just removing all dependencies, as this is a repo for addons and not all of them will be used, you may add those you need in your repo.

**Comment by moylop260** [comment]
+1 to remove them or just rename the file

**Comment by randall-vx** [comment]
Done ! @moylop260 @luisg123v 

Thanks for the comments !

Regards,

**Comment by luisg123v** [comment]
@randall-vx remember to **always** squash your commits. I merged squashing to avoid issues.

**Comment by randall-vx** [comment]
@luisg123v Thank you ! :+1:

**Pull request merged**
